### ISSUE TITLE
Cannot launch due to missing shared libraries

### ISSUE THREAD

**Issue by ramirez7** [Daniikk-1012/Time-Saver#1]
I get this error when I try to run the jar:
```
$ java -jar time-saver.jar 
[LwjglApplication] Couldn't initialize audio, disabling audio
java.lang.UnsatisfiedLinkError: /tmp/libgdxarmando/dd5c1a65/liblwjgl64.so: libXxf86vm.so.1: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1946)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1828)
        at java.lang.Runtime.load0(Runtime.java:810)
        at java.lang.System.load(System.java:1088)
        at org.lwjgl.Sys$1.run(Sys.java:70)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
        at org.lwjgl.Sys.loadLibrary(Sys.java:87)
        at org.lwjgl.Sys.<clinit>(Sys.java:117)
        at org.lwjgl.openal.AL.<clinit>(AL.java:59)
        at com.badlogic.gdx.backends.lwjgl.audio.OpenALLwjglAudio.<init>(OpenALLwjglAudio.java:71)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.createAudio(LwjglApplication.java:278)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:90)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:71)
        at com.wgsoft.game.timesaver.desktop.DesktopLauncher.main(DesktopLauncher.java:14)
Exception in thread "LWJGL Application" java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.Sys
        at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:617)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:125)
```

## System Info

```
$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

OS: Linux (NixOS 20.03)

**Comment by ramirez7** [comment]
I tried running in a `nix-shell -p jdk8 -p xorg.libXxf86vm` (as suggested by @Daniikk-1012) and got the same error.

**Comment by Daniikk-1012** [comment]
What is the architecture of your PC?

**Comment by Daniikk1012** [comment]
Try the 1.0-beta.2 version of the game, this issue should be fixed now
